sudo: required
services:
  - docker

before_install:
  - docker build -t kiransaras/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kiransaras/react-test npm test -- --coverage
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
 - docker build -t kiransaras/multi-client ./client
 - docker build -t kiransaras/multi-nginx ./nginx
 - docker build -t kiransaras/multi-server ./server
 - docker build -t kiransaras/multi-worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push kiransaras/multi-client
 - docker push kiransaras/multi-nginx 
 - docker push kiransaras/multi-server
 - docker push kiransaras/multi-worker
